### ISSUE TITLE
Your link to the deployed version is HTTP not HTTPS

### ISSUE THREAD

**Issue by owencm** [lewiscowper/serviceworker-demo#4]
SW doesn't get installed on HTTP so the link should go to your HTTPS site (or you should redirect on the server side)

**Comment by lewiscowper** [comment]
You are correct, I have only used it in presentations running locally, and definitely missed that. Have updated the link accordingly.

Thanks for the report!


[![selfie-1](http://i.imgur.com/CPOKHHB.gif)](https://github.com/thieman/github-selfies/)
